#!/usr/bin/env perl

use strict;
use warnings;

sub main {
    my $pacmd = `pacmd list-sink-inputs`;
    s/\n//g, s/\s+/ /g for $pacmd; # little cleanup
    my ($state, $name, $artist) = $pacmd =~ /index.*state: (.*?) sink.*?<Lollypop>.*?media.title = "(.*?)".*media.artist = "(.*?)"/;
    if ($name && $artist) {
        my $icon = $state =~ m/running/i ? '' : '';
        print "$icon $name - $artist ";
    } else {
        print "";
    }
}

main();
